plugins:
  - jasmine  

env:
  browser: true
  jasmine: true

globals:
  moment: true
  bard: true

extends: ['eslint:recommended','plugin:jasmine/recommended']

rules:
  quotes:
    - error
    - single
  semi:
    - error
    - always
 


